# .github/workflows/docker-deploy.yml

name: Docker Build and Deploy

# 이벤트를 정의합니다. 예를 들어, main 브랜치에 푸시될 때 실행합니다.
on:
  push:
    branches:
      - master

jobs:
  build:
    # Self-hosted Runner에서 실행되도록 설정합니다.
    runs-on: self-hosted

    steps:
      # 1. GitHub 저장소의 코드를 체크아웃합니다.
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Docker 로그인을 수행합니다. (Docker Hub 인증 정보를 GitHub Secrets에 등록해야 합니다)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Docker 이미지를 빌드합니다.
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # 4. Docker 이미지를 Docker Hub에 태그하고 푸시합니다.
      - name: Push Docker image to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

